{{- include "ocis.appNames" (dict "scope" . "appName" "appNameWeb" "appNameSuffix" "") -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .appName }}-config
  namespace: {{ template "ocis.namespace" . }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
data:
  web.yaml: |
    ---
    web:
      config:
        {{- if gt (len .Values.services.web.config.styles) 0 }}
        styles:
          {{- toYaml .Values.services.web.config.styles | nindent 10 }}
        {{- end }}
        {{- if gt (len .Values.services.web.config.scripts) 0 }}
        scripts:
          {{- toYaml .Values.services.web.config.scripts | nindent 10 }}
        {{- end }}
        {{- if gt (len .Values.services.web.config.apps) 0 }}
        apps:
          {{- toYaml .Values.services.web.config.apps | nindent 10 }}
        {{- end }}
        {{- if gt (len .Values.services.web.config.externalApplications) 0 }}
        external_apps:
          {{- toYaml .Values.services.web.config.externalApplications | nindent 10 }}
        {{- end }}
        {{- if gt (len .Values.services.web.config.applications) 0 }}
        applications:
          {{- toYaml .Values.services.web.config.applications | nindent 10 }}
        {{- end }}
        options:
          contextHelpersReadMore: {{ .Values.services.web.config.contextHelpersReadMore.enabled }}
          disableFeedbackLink: {{ not .Values.services.web.config.feedbackLink.enabled }}
          {{- if .Values.services.web.config.feedbackLink.enabled }}
          {{- if (or .Values.services.web.config.feedbackLink.href .Values.services.web.config.feedbackLink.ariaLabel .Values.services.web.config.feedbackLink.description) }}
          feedbackLink:
            {{- if .Values.services.web.config.feedbackLink.href  }}
            href: {{ .Values.services.web.config.feedbackLink.href | quote }}
            {{- end }}
            {{- if .Values.services.web.config.feedbackLink.ariaLabel  }}
            ariaLabel: {{ .Values.services.web.config.feedbackLink.ariaLabel | quote }}
            {{- end }}
            {{- if .Values.services.web.config.feedbackLink.description }}
            description: {{ .Values.services.web.config.feedbackLink.description | quote }}
            {{- end }}
          {{- end }}
          {{- end }}
          {{- if gt (len .Values.services.web.config.previewFileMimeTypes) 0 }}
          previewFileMimeTypes:
            {{- toYaml .Values.services.web.config.previewFileMimeTypes | nindent 12 }}
          {{- end }}
          {{- if .Values.features.externalUserManagement.oidc.sessionManagementLink }}
          logoutUrl: {{ .Values.features.externalUserManagement.oidc.sessionManagementLink | quote }}
          {{- end }}
          {{- if .Values.features.externalUserManagement.oidc.editAccountLink }}
          accountEditLink:
            href: {{ .Values.features.externalUserManagement.oidc.editAccountLink | quote }}
          {{- end }}
